export const mockTableProject = [
  {
    id: 33,
    link: 'www.wdtrack.wiredelta.com',
    name: 'TimerV3',
    created: new Date(),
    issues: [
      {
        id: 17,
        name: 'Youtube link does not work',
        created: new Date(),
        status: 'pending',
      }
    ],
    managedBy: 'John Doe',
    users: [
      {
        name: 'Bart Simpson',
        phone: '+45 117233',
        email: 'bartsimpson@gmail.com',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Meggie Simpson',
        phone: '+45 117923',
        email: 'meggiesimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Lisa Simpson',
        phone: '+45 607923',
        email: 'lisasimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'project management',
      },
    ],
    status: true,
  },
  {
    id: 33,
    link: 'growcarrots.dk',
    name: 'growcarrots.dk',
    created: new Date(),
    issues: [
      {
        id: 17,
        name: 'Error 404',
        created: new Date(),
        status: 'active',
      },
      {
        id: 17,
        name: 'Preloader broken animation',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Does not communicate with database',
        created: new Date(),
        status: 'closed',
      }
    ],
    managedBy: 'Peter Griffin',
    users: [
      {
        name: 'Bart Simpson',
        phone: '+45 117233',
        email: 'bartsimpson@gmail.com',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Meggie Simpson',
        phone: '+45 117923',
        email: 'meggiesimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Lisa Simpson',
        phone: '+45 607923',
        email: 'lisasimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'project management',
      },
    ],
    status: true,
  },
  {
    id: 33,
    link: 'www.pmiiqos/shop.dk',
    name: 'PMI Iqos - e-shop',
    created: new Date(),
    issues: [
      {
        id: 17,
        name: 'Error 404',
        created: new Date(),
        status: 'active',
      },
      {
        id: 17,
        name: 'Preloader broken animation',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Does not communicate with database',
        created: new Date(),
        status: 'closed',
      },
      {
        id: 17,
        name: 'Header is too on top',
        created: new Date(),
        status: 'closed',
      }
    ],
    managedBy: 'Peter Griffin',
    users: [
      {
        name: 'Bart Simpson',
        phone: '+45 117233',
        email: 'bartsimpson@gmail.com',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Meggie Simpson',
        phone: '+45 117923',
        email: 'meggiesimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Lisa Simpson',
        phone: '+45 607923',
        email: 'lisasimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'project management',
      },
      {
        name: 'Bender Black',
        phone: '+45 607203',
        email: 'benderfuture@gmail.wd.dk',
        imageUrl: '',
        department: 'client',
      },
    ],
    status: true,
  },
  {
    id: 33,
    link: 'www.wdtrack.wiredelta.com',
    name: 'TimerV3',
    created: new Date(),
    issues: [
      {
        id: 17,
        name: 'Video does not work',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Mobile responsive issue',
        created: new Date(),
        status: 'pending',
      },
    ],
    managedBy: 'John Doe',
    users: [
      {
        name: 'Bart Simpson',
        phone: '+45 117233',
        email: 'bartsimpson@gmail.com',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Meggie Simpson',
        phone: '+45 117923',
        email: 'meggiesimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'development',
      },
    ],
    status: true,
  },
  {
    id: 33,
    link: 'www.wdtrack.wiredelta.com',
    name: 'Bobs burgers',
    created: new Date(),
    issues: [
      {
        id: 17,
        name: 'Video does not work',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Mobile responsive issue',
        created: new Date(),
        status: 'pending',
      },
    ],
    managedBy: 'Homer Simpson',
    users: [
      {
        name: 'Bart Simpson',
        phone: '+45 117233',
        email: 'bartsimpson@gmail.com',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Meggie Simpson',
        phone: '+45 117923',
        email: 'meggiesimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'development',
      },
    ],
    status: true,
  },
  {
    id: 33,
    link: 'www.wdtrack.wiredelta.com',
    name: 'TimerV3',
    created: new Date(),
    issues: [
      {
        id: 17,
        name: 'Video does not work',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Mobile responsive issue',
        created: new Date(),
        status: 'pending',
      },
    ],
    managedBy: 'John Doe',
    users: [
      {
        name: 'Bart Simpson',
        phone: '+45 117233',
        email: 'bartsimpson@gmail.com',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Meggie Simpson',
        phone: '+45 117923',
        email: 'meggiesimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'development',
      },
    ],
    status: true,
  },
  {
    id: 33,
    link: 'www.wdtrack.wiredelta.com',
    name: 'Nike e-shop',
    created: new Date(),
    issues: [
      {
        id: 17,
        name: 'Video does not work',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Mobile responsive issue',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Mobile responsive issue',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Mobile responsive issue',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Mobile responsive issue',
        created: new Date(),
        status: 'pending',
      },
      {
        id: 17,
        name: 'Mobile responsive issue',
        created: new Date(),
        status: 'pending',
      },
    ],
    managedBy: 'Philip Hampson Knight',
    users: [
      {
        name: 'Bart Simpson',
        phone: '+45 117233',
        email: 'bartsimpson@gmail.com',
        imageUrl: '',
        department: 'development',
      },
      {
        name: 'Meggie Simpson',
        phone: '+45 117923',
        email: 'meggiesimpson@gmail.wd.dk',
        imageUrl: '',
        department: 'development',
      },
    ],
    status: true,
  },
];
